{{- if .Values.global.configCluster }}
apiVersion: v1
{{- end }}
kind: ServiceAccount
{{- end }}
  {{- if .Values.global.imagePullSecrets }}
{{- end }}
imagePullSecrets:
{{- end }}
  {{- range .Values.global.imagePullSecrets }}
{{- end }}
  - name: {{ . }}
{{- end }}
  {{- end }}
{{- end }}
  {{- end }}
{{- end }}
metadata:
{{- end }}
  name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
{{- end }}
  namespace: {{ .Values.global.istioNamespace }}
{{- end }}
  labels:
{{- end }}
    app: istiod
{{- end }}
    release: {{ .Release.Name }}
{{- end }}
---
{{- end }}
